const fotos = [
    {
        id: 0,
        categoria: 'motocross',
        images: {
            1: "/images/motos/1.jpg",
            2: "/images/motos/2.jpg",
            3: "/images/motos/3.jpg",
            4: "/images/motos/4.jpg",
            5: "/images/motos/5.jpg",
            6: "/images/motos/6.jpg",
            7: "/images/motos/7.jpg",
            8: "/images/motos/8.jpg",
            9: "/images/motos/9.jpg",
            10: "/images/motos/10.jpg",
            11: "/images/motos/11.jpg",
            12: "/images/motos/12.jpg",
            13: "/images/motos/13.jpg",
            14: "/images/motos/14.jpg",
            15: "/images/motos/15.jpg",
            16: "/images/motos/16.jpg",
            17: "/images/motos/17.jpg",
            18: "/images/motos/18.jpg",
            19: "/images/motos/19.jpg",
            20: "/images/motos/20.jpg"


        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }
    },
    {
        id: 1,
        categoria: 'rally',
        images: {
            1: "/images/rally/1.jpg",
            2: "/images/rally/2.jpg",
            3: "/images/rally/3.jpg",
            4: "/images/rally/4.jpg",
            5: "/images/rally/5.jpg",
            6: "/images/rally/6.jpg",
            7: "/images/rally/7.jpg",
            8: "/images/rally/8.jpg",
            9: "/images/rally/9.jpg",
            10: "/images/rally/10.jpg",
            11: "/images/rally/11.jpg",
            12: "/images/rally/12.jpg",
            13: "/images/rally/13.jpg",
            14: "/images/rally/14.jpg",
            15: "/images/rally/15.jpg",
            16: "/images/rally/16.jpg",
            17: "/images/rally/17.jpg",
            18: "/images/rally/18.jpg",
            19: "/images/rally/19.jpg",
            20: "/images/rally/20.jpg"
        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }

    },
    {
        id: 2,
        categoria: 'futbol',
        images: {
            1: "/images/motos/1.jpg",
            2: "/images/motos/2.jpg",
            3: "/images/motos/3.jpg",
            4: "/images/motos/4.jpg",
            5: "/images/motos/5.jpg",
            6: "/images/motos/6.jpg",
            7: "/images/motos/7.jpg",
            8: "/images/motos/8.jpg",
            9: "/images/motos/9.jpg",
            10: "/images/motos/10.jpg",
            11: "/images/motos/11.jpg",
            12: "/images/motos/12.jpg",
            13: "/images/motos/13.jpg",
            14: "/images/motos/14.jpg",
            15: "/images/motos/15.jpg",
            16: "/images/motos/16.jpg",
            17: "/images/motos/17.jpg",
            18: "/images/motos/18.jpg",
            19: "/images/motos/19.jpg",
            20: "/images/motos/20.jpg"


        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }
    },
    {
        id: 3,
        categoria: 'dron',
        images: {
            1: "/images/rally/1.jpg",
            2: "/images/rally/2.jpg",
            3: "/images/rally/3.jpg",
            4: "/images/rally/4.jpg",
            5: "/images/rally/5.jpg",
            6: "/images/rally/6.jpg",
            7: "/images/rally/7.jpg",
            8: "/images/rally/8.jpg",
            9: "/images/rally/9.jpg",
            10: "/images/rally/10.jpg",
            11: "/images/rally/11.jpg",
            12: "/images/rally/12.jpg",
            13: "/images/rally/13.jpg",
            14: "/images/rally/14.jpg",
            15: "/images/rally/15.jpg",
            16: "/images/rally/16.jpg",
            17: "/images/rally/17.jpg",
            18: "/images/rally/18.jpg",
            19: "/images/rally/19.jpg",
            20: "/images/rally/20.jpg"
        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }

    }, {
        id: 4,
        categoria: 'ByN',
        images: {
            1: "/images/motos/1.jpg",
            2: "/images/motos/2.jpg",
            3: "/images/motos/3.jpg",
            4: "/images/motos/4.jpg",
            5: "/images/motos/5.jpg",
            6: "/images/motos/6.jpg",
            7: "/images/motos/7.jpg",
            8: "/images/motos/8.jpg",
            9: "/images/motos/9.jpg",
            10: "/images/motos/10.jpg",
            11: "/images/motos/11.jpg",
            12: "/images/motos/12.jpg",
            13: "/images/motos/13.jpg",
            14: "/images/motos/14.jpg",
            15: "/images/motos/15.jpg",
            16: "/images/motos/16.jpg",
            17: "/images/motos/17.jpg",
            18: "/images/motos/18.jpg",
            19: "/images/motos/19.jpg",
            20: "/images/motos/20.jpg"


        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }
    }, {
        id: 5,
        categoria: 'varios',
        images: {
            1: "/images/rally/1.jpg",
            2: "/images/rally/2.jpg",
            3: "/images/rally/3.jpg",
            4: "/images/rally/4.jpg",
            5: "/images/rally/5.jpg",
            6: "/images/rally/6.jpg",
            7: "/images/rally/7.jpg",
            8: "/images/rally/8.jpg",
            9: "/images/rally/9.jpg",
            10: "/images/rally/10.jpg",
            11: "/images/rally/11.jpg",
            12: "/images/rally/12.jpg",
            13: "/images/rally/13.jpg",
            14: "/images/rally/14.jpg",
            15: "/images/rally/15.jpg",
            16: "/images/rally/16.jpg",
            17: "/images/rally/17.jpg",
            18: "/images/rally/18.jpg",
            19: "/images/rally/19.jpg",
            20: "/images/rally/20.jpg"
        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }

    },
]
