const fotos = [
    {
        id: 0,
        categoria: 'motocross',
        images: {
            1: "/images/motos/1.jpg",
            2: "/images/motos/2.jpg",
            3: "/images/motos/3.jpg",
            4: "/images/motos/4.jpg",
            5: "/images/motos/5.jpg",
            6: "/images/motos/6.jpg",
            7: "/images/motos/7.jpg",
            8: "/images/motos/8.jpg",
            9: "/images/motos/9.jpg",
            10: "/images/motos/10.jpg",
            11: "/images/motos/11.jpg",
            12: "/images/motos/12.jpg",
            13: "/images/motos/13.jpg",
            14: "/images/motos/14.jpg",
            15: "/images/motos/15.jpg",
            16: "/images/motos/16.jpg",
            17: "/images/motos/17.jpg",
            18: "/images/motos/18.jpg",
            19: "/images/motos/19.jpg",
            20: "/images/motos/20.jpg"


        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }
    },
    {
        id: 1,
        categoria: 'rally',
        images: {
            1: "/images/rally/1.jpg",
            2: "/images/rally/2.jpg",
            3: "/images/rally/3.jpg",
            4: "/images/rally/4.jpg",
            5: "/images/rally/5.jpg",
            6: "/images/rally/6.jpg",
            7: "/images/rally/7.jpg",
            8: "/images/rally/8.jpg",
            9: "/images/rally/9.jpg",
            10: "/images/rally/10.jpg",
            11: "/images/rally/11.jpg",
            12: "/images/rally/12.jpg",
            13: "/images/rally/13.jpg",
            14: "/images/rally/14.jpg",
            15: "/images/rally/15.jpg",
            16: "/images/rally/16.jpg",
            17: "/images/rally/17.jpg",
            18: "/images/rally/18.jpg",
            19: "/images/rally/19.jpg",
            20: "/images/rally/20.jpg"
        },
        trabajo: {
            1: "World Rally Car - 2019",
            2: "World Rally Car - 2019",
            3: "World Rally Car - 2019",
            4: "World Rally Car - 2019",
            5: "World Rally Car - 2019",
            6: "World Rally Car - 2019",
            7: "World Rally Car - 2019",
            8: "World Rally Car - 2019",
            9: "World Rally Car - 2019",
            10: "World Rally Car - 2019",
            11: "World Rally Car - 2019",
            12: "World Rally Car - 2019",
            13: "World Rally Car - 2019",
            14: "World Rally Car - 2019",
            15: "World Rally Car - 2019",
            16: "World Rally Car - 2019",
            17: "World Rally Car - 2019",
            18: "World Rally Car - 2019",
            19: "World Rally Car - 2019",
            20: "World Rally Car - 2019"

        }

    },
    {
        id: 2,
        categoria: 'futbol',
        images: {
            1: "/images/belgrano/1.jpg",
            2: "/images/belgrano/2.jpg",
            3: "/images/belgrano/3.jpg",
            4: "/images/belgrano/4.jpg",
            5: "/images/belgrano/5.jpg",
            6: "/images/belgrano/6.jpg",
            7: "/images/belgrano/7.jpg",
            8: "/images/belgrano/8.jpg",
            9: "/images/belgrano/9.jpg",
            10: "/images/belgrano/10.jpg",
            11: "/images/belgrano/11.jpg",
            12: "/images/belgrano/12.jpg",
            13: "/images/belgrano/13.jpg",
            14: "/images/belgrano/14.jpg",
            15: "/images/belgrano/15.jpg",
            16: "/images/belgrano/16.jpg",
            17: "/images/belgrano/17.jpg",
            18: "/images/belgrano/18.jpg",
            19: "/images/belgrano/19.jpg",
            20: "/images/belgrano/20.jpg"


        },
        trabajo: {
            1: "Club Atlético Belgrano - 2019",
            2: "Club Atlético Belgrano - 2019",
            3: "Club Atlético Belgrano - 2019",
            4: "Club Atlético Belgrano - 2019",
            5: "Club Atlético Belgrano - 2019",
            6: "Club Atlético Belgrano - 2019",
            7: "Club Atlético Belgrano - 2019",
            8: "Club Atlético Belgrano - 2019",
            9: "Club Atlético Belgrano - 2019",
            10: "Club Atlético Belgrano - 2019",
            11: "Club Atlético Belgrano - 2019",
            12: "Club Atlético Belgrano - 2019",
            13: "Club Atlético Belgrano - 2019",
            14: "Club Atlético Belgrano - 2019",
            15: "Club Atlético Belgrano - 2019",
            16: "Club Atlético Belgrano - 2019",
            17: "Club Atlético Belgrano - 2019",
            18: "Club Atlético Belgrano - 2019",
            19: "Club Atlético Belgrano - 2019",
            20: "Club Atlético Belgrano - 2019"

        }
    },
    {
        id: 3,
        categoria: 'dron',
        images: {
            1: "/images/dron/1.jpg",
            2: "/images/dron/2.jpg",
            3: "/images/dron/3.jpg",
            4: "/images/dron/4.jpg",
            5: "/images/dron/5.jpg",
            6: "/images/dron/6.jpg",
            7: "/images/dron/7.jpg",
            8: "/images/dron/8.jpg",
            9: "/images/dron/9.jpg",
            10: "/images/dron/10.jpg",
            11: "/images/dron/11.jpg",
            12: "/images/dron/12.jpg",
            13: "/images/dron/13.jpg",
            14: "/images/dron/14.jpg",
            15: "/images/dron/15.jpg",
            16: "/images/dron/16.jpg",
            17: "/images/dron/17.jpg",
            18: "/images/dron/18.jpg",
            19: "/images/dron/19.jpg",
            20: "/images/dron/20.jpg"
        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }

    }, {
        id: 4,
        categoria: 'byn',
        images: {
            1: "/images/byn/1.jpg",
            2: "/images/byn/2.jpg",
            3: "/images/byn/3.jpg",
            4: "/images/byn/4.jpg",
            5: "/images/byn/5.jpg",
            6: "/images/byn/6.jpg",
            7: "/images/byn/7.jpg",
            8: "/images/byn/8.jpg",
            9: "/images/byn/9.jpg",
            10: "/images/byn/10.jpg",
            11: "/images/byn/11.jpg",
            12: "/images/byn/12.jpg",
            13: "/images/byn/13.jpg",
            14: "/images/byn/14.jpg",
            15: "/images/byn/15.jpg",
            16: "/images/byn/16.jpg",
            17: "/images/byn/17.jpg",
            18: "/images/byn/18.jpg",
            19: "/images/byn/19.jpg",
            20: "/images/byn/20.jpg"


        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }
    }, {
        id: 5,
        categoria: 'varios',
        images: {
            1: "/images/varios/1.jpg",
            2: "/images/varios/2.jpg",
            3: "/images/varios/3.jpg",
            4: "/images/varios/4.jpg",
            5: "/images/varios/5.jpg",
            6: "/images/varios/6.jpg",
            7: "/images/varios/7.jpg",
            8: "/images/varios/8.jpg",
            9: "/images/varios/9.jpg",
            10: "/images/varios/10.jpg",
            11: "/images/varios/11.jpg",
            12: "/images/varios/12.jpg",
            13: "/images/varios/13.jpg",
            14: "/images/varios/14.jpg",
            15: "/images/varios/15.jpg",
            16: "/images/varios/16.jpg",
            17: "/images/varios/17.jpg",
            18: "/images/varios/18.jpg",
            19: "/images/varios/19.jpg",
            20: "/images/varios/20.jpg"
        },
        trabajo: {
            1: "Enduro del verano - 2019",
            2: "Enduro del verano - 2019",
            3: "Enduro del verano - 2019",
            4: "Enduro del verano - 2019",
            5: "Enduro del verano - 2019",
            6: "Enduro del verano - 2019",
            7: "Enduro del verano - 2019",
            8: "Enduro del verano - 2019",
            9: "Enduro del verano - 2019",
            10: "Enduro del verano - 2019",
            11: "Enduro del verano - 2019",
            12: "Enduro del verano - 2019",
            13: "Enduro del verano - 2019",
            14: "Enduro del verano - 2019",
            15: "Enduro del verano - 2019",
            16: "Enduro del verano - 2019",
            17: "Enduro del verano - 2019",
            18: "Enduro del verano - 2019",
            19: "Enduro del verano - 2019",
            20: "Enduro del verano - 2019"

        }

    },
]
